config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts

  resources :tenants do 
    resources :projects do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  root to: "home#index"

  as(:user) do
    match '/user/confirmation' => 'confirmations#update', via: :put, as: :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :confirmations => "confirmations",
    :registrations => "registrations"
    # :sessions => "XXXX",
    # :passwords => "XXX" 
  }

  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container">

    <%= link_to ("<i class='fa fa-rocket'></i> Project Management App").html_safe, root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user && current_user.is_admin? %>
          <li class="nav-item">
            <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe, new_member_path, class: 'navbar-link btn btn-primary me-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "<i class='fa fa-briefcase'></i> Change Plan".html_safe, edit_plan_path, class: 'btn btn-primary navbar-link' %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="col-md-9 nav-item">
            <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile', class: 'nav-link' %>
          </li>
          <li class="col-md-3 logout">
            <%= button_to 'Logout', destroy_user_session_path, class:'btn btn-danger', method: :delete, data: { turbo: false } %>
          </li>
        <% else %>
          <li>
            <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/common/_navbar.old.html.erb
<nav class="navbar navbar-static-top navbar-expand-lg bg-dark navbar-dark">
  <div class="container">
    <%= link_to ("<i class='fa fa-rocket'></i> Project Management App").html_safe, root_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user && current_user.is_admin? %>
          <li class="nav-item">
            <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe, new_member_path, class: 'navbar-link btn btn-primary me-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "<i class='fa fa-briefcase'></i> Change Plan".html_safe, edit_plan_path, class: 'btn btn-primary navbar-link' %>
          </li>
        <% end %>

      <ul class="navbar-nav">
        <div class="d-flex justivy-content-end">
              <% if current_user %>
            <li class="col-md-8 nav-item">
              <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile', class: 'nav-link' %>
            </li>
            <li class="col-md-1">&nbsp;</li>
            <li class="col-md-3 logout">
              <%= button_to 'Logout', destroy_user_session_path, class:'btn btn-danger', method: :delete, data: { turbo: false } %>
            </li>
          <% else %>
            <li class="pull-right">
              <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
            </li>
          <% end %>
        </div>

      </ul>
    </div>
  </div>
</nav>